@extends('backend.customer.appback')

@section('title','Records Profits')


@section('style')
    <style>
        .btn-dark{
            margin-right: 140px;
        }
        p{
          display: inline;
          font-size: 15px;
        }

    </style>
@endsection

@section('content2')

<div class="">
    <h5>Note: When you click on any store, you can see the records of each store generated by their own orders</h5>
</div>
<br>
<div class="col-sm-6" style="margin: auto; margin-bottom:25px;">
    <div class="card widget-flat" style="background-image:linear-gradient(315deg, #2123e1cb 0%, #0e0744 74%); text-align:center;">
        <div class="card-body">
            <div class="float-end">
                <i class="mdi mdi-cart-plus widget-icon bg-danger-lighten text-danger"></i>
            </div>
            <h5 class=" fw-normal mt-0" title="Number of Orders" style="color: white;">All Profits</h5>
            <h3 class="mt-3 mb-3" style="color: white;">{{auth()->user()->balance}} USD</h3>
        </div> <!-- end card-body-->
    </div> <!-- end card-->
</div>
<div class="row row-cols-1 row-cols-md-3 g-4">
    @forelse (auth()->user()->stores as $item)
    <div class="col">
      <div class="card h-100">
        <img src="{{asset($item->Baner)}}" class="card-img-top" alt="..." width="100px" height="150px">
        <div class="card-body">
          <h5 class="card-title"> name :{{ $item->name_store }}</h5>
          <a href="{{route('profit.profitstore',$item->id)}}"><button type="button" class="btn btn-secondary">
            View <span class="badge badge-light"><p> ({{ $item->profit()->count() }})Record </p></span>
            <span class="sr-only">unread messages</span>
          </button> </a>

        </div>
      </div>
    </div>
@empty
<div class="empety">
    <h5 class="text-center">There are no Profits available for you 🙂 😔</h5>
</div>
@endforelse


@endsection
